### ISSUE TITLE
ZINC20 is downloaded?

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8a5g#1]
Hi, 
does this model require downloading ZINC20 for the search or it needs internet connection? Can you clarify that for the documentation?

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron 
Just saw the open issue on this model and think to reply on it as i've worked on it.
It downloaded the zinc-instock in your system cache only for the first time when you run the model, after that it uses that downloaded file from cache to make the model work. Like this
```
(model-eos8a5g) zakia@DESKTOP-I2B0R5O:~/eos8a5g/model/framework$ bash run_predict.sh $FRAMEWORK_PATH $FRAMEWORK_PATH/input.csv $FRAMEWORK_PATH/output.csv
Starting zinc-instock download to cache directory /home/zakia/.cache/molbloom
Downloading filter... 100%
bloom_read: loaded bloom filter size=838776913 bits, MB=99.989998, k=62
```
Thanks

**Comment by GemmaTuron** [comment]
Thanks @ZakiaYahya !
