### ISSUE TITLE
Clean UP & Dockerization eos8a5g

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8a5g#3]

**Comment by ZakiaYahya** [comment]
I've made following changes in the model for refactoring purpose. 
(1) Deleted all` .dvc` folders and files
(2) Updated the `LICENSE` file to GNU
(3) Deleted `run_search.sh` from **framework** folder
(4) Rename `run_predict.sh` to `run.sh `
(5) Change `search` api in **service.py** to `run` api


Refactor the model and tested it with `few smiles` and even with `eml_canonical` to ensure that model is working. Tested the model both with `run.sh` and `--repo-path` before and after refactoring. The model is working fine. 
I've Open PR on it. Kindly check it.
Thanks
